version: "3.3"

# store nginx key and cert in swarm secrets.
# Note: run it with UCP client bundle.

services:
  ng:
    image: xinfengliu/nginx:stable-alpine-tls
    deploy:
      replicas: 1
    secrets:
      - source: nginx.crt
        target: /run/secrets/nginx.crt
      - source: nginx.key
        target: /run/secrets/nginx.key
    ports:
      - mode: host
        published: 8000
        target: 80
      - mode: host
        published: 9443
        target: 443
secrets:
  nginx.crt:
    file: ./nginx.crt
  nginx.key:
    file: ./nginx.key
